{
 "title": "Falco Dashboard",
 "description": "Grafana dashboard for Falco output events",
 "time": { "from": "now-40m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(falco_events[5m])", "legendFormat": "{{rule}} ({{hostname}})" }
   ]
  },
  {
   "title": "Event ditribution by priority",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(priority) (falco_events)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Violated Rules",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(rule) (falco_events)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Totals",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 11 },
   "targets": [
    { "expr": "falco_events" }
   ]
  }
 ]
}